name = "MultivariateSingularIntegrals"
uuid = "afb3ad05-8577-40d5-8767-20c5aa8ee3cd"
authors = ["Sheehan Olver <solver@mac.com>"]
version = "0.1.0"

[deps]
ClassicalOrthogonalPolynomials = "b30e2e7b-c4ee-47da-9d5f-2c5c27239acd"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SingularIntegrals = "d7440221-8b5e-42fc-909c-0567823f424a"

[compat]
ClassicalOrthogonalPolynomials = "0.15.1"
DoubleFloats = "1"
FillArrays = "1.13.0"
LinearAlgebra = "1"
QuadGK = "2.11.2"
SingularIntegrals = "0.3.8"
Test = "1"
julia = "1.10"

[extras]
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DoubleFloats", "QuadGK"]
